spring:
  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin

    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

cloud:
  openfeign:
    client:
      config:
        default:
          connectTimeout: ${FEIGN_CONNECT_TIMEOUT}
          readTimeout: ${FEIGN_READ_TIMEOUT}
          loggerLevel: ${FEIGN_LOGGER_LEVEL}


oauth:
  google:
    android:
      client-id: ${ANDROID_CLIENT_ID}
      redirect-uri: ${ANDROID_REDIRECT_URI}
    ios:
      client-id: ${IOS_CLIENT_ID}
      redirect-uri: ${IOS_REDIRECT_URI}
    web:
      client-id: ${WEB_CLIENT_ID}
      client-secret: ${WEB_CLIENT_SECRET}
      redirect-uri: ${WEB_REDIRECT_URI}

  apple:
    team-id: ${APPLE_TEAM_ID}
    key-id: ${APPLE_KEY_ID}
    client-id: ${APPLE_CLIENT_ID}
    redirect-uri: ${APPLE_REDIRECT_URI}
    private-key-pem: |-
      ${APPLE_PRIVATE_KEY_PEM}

ncp:
  s3:
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    region: kr-standard
    endpoint: https://kr.object.ncloudstorage.com
    bucket: ${NCP_BUCKET_NAME}

swagger:
  server-url: ${SERVER_URL}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
